### ISSUE TITLE
Why do you title with "Compute instance-level reliability" in your jupyternotebook?

### ISSUE THREAD

**Issue by tangxiangru** [julmaxi/summary_lq_analysis#1]

**Comment by julmaxi** [comment]
This refers to the Krippendorff's alpha from section 4.1
It is called instance level in the notebook, because it refers to the reliability of the annotations at the summary (=instance) level.

**Comment by tangxiangru** [comment]
Thanks.
But in your paper, you are using "system-level comparison", do they have any difference?

**Comment by julmaxi** [comment]
The system level reliability (i.e. the split-half reliability) is computed in the next section (titled "Compute SHR"). I agree this could be labeled a bit more clearly so I updated the headings in the notebook. Does that answer your question?

**Comment by tangxiangru** [comment]
Thanks a lot!
